### PR TITLE
Update dependency versions in nuspec

### LINKED ISSUE #15: Dependency mismatch between nuspec and project
The project file contains explicit dependencies on Topshelf 4.2.0 and Unity.Abstractions 5.11.1, but the nuspec allows for lower versions.

One or the other should be changed.

Unless there are objections, or someone else gets to it first, I'll submit a PR to update the nuspec to 4.2.0 & 5.11.1 today when I have the opportunity.

### PR DESCRIPTION
**Pull request by Kesmy**
Update the dependency versions in the nuspec to match the project's compile-time dependencies.

Resolves #15

### CODE REVIEW

**Comment by Kesmy** [comment]
@alexandrnikitin The only thing here I did not touch is the readme, which I will leave for you unless you would like it updated.

I updated the version to 4.1.0, but this could maybe be a 4.0.1? I don't think this change would be surprising to consumers, since they would presumably already be using the newer packages with 4.0.0

**Comment by alexandrnikitin** [comment]
@Kesmy What if downgrade the dependecies to the nuspec lower bounds? Here's a PR for it #18 WDYT?

**Comment by alexandrnikitin** [comment]
I tested it using the sample project and there are no compiler issue with dependencies.

**Comment by Kesmy** [comment]
@alexandrnikitin Lowering the dependencies in the other PR is also valid. Since you're OK with a change to support netstandard, this one can be abandoned... Upgrading the packages will happen naturally as part of that support.

**Pull request closed without merging**
